# Generated by Django 5.2.3 on 2025-06-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('measure', models.CharField(help_text='Укажите единицу измерения', max_length=50, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рецепта')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('time', models.PositiveSmallIntegerField(help_text='Укажите время', verbose_name='Время приготовления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/photos', verbose_name='Изображение блюда')),
                ('fav', models.BooleanField(default=False, verbose_name='В избранном')),
                ('cart', models.BooleanField(default=False, verbose_name='В корзине')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'блюда',
            },
        ),
        migrations.CreateModel(
            name='RecipesComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Укажите число в выбранных единицах', verbose_name='Количество')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.component', verbose_name='Компонент')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'состав блюда',
                'verbose_name_plural': 'состав блюд',
            },
        ),
        migrations.AddField(
            model_name='recipes',
            name='components',
            field=models.ManyToManyField(related_name='dishes', through='recipes.RecipesComponent', to='recipes.component'),
        ),
    ]
